/** Países para selectores (nombre en mayúsculas, como se guarda). Los más usados primero. */
export const PAISES_FRECUENTES = ["PARAGUAY", "BOLIVIA", "ARGENTINA", "BRASIL", "URUGUAY", "CHILE"];

export const PAISES = [
  "ALEMANIA", "ARABIA SAUDITA", "ARGENTINA", "AUSTRALIA", "AUSTRIA", "BÉLGICA", "BOLIVIA", "BRASIL",
  "CANADÁ", "CHILE", "CHINA", "COLOMBIA", "COREA DEL SUR", "COSTA RICA", "CUBA", "DINAMARCA",
  "ECUADOR", "EGIPTO", "EL SALVADOR", "EMIRATOS ÁRABES UNIDOS", "ESPAÑA", "ESTADOS UNIDOS", "FILIPINAS",
  "FINLANDIA", "FRANCIA", "GRECIA", "GUATEMALA", "HONDURAS", "HONG KONG", "INDIA", "INDONESIA",
  "IRLANDA", "ISRAEL", "ITALIA", "JAPÓN", "MALASIA", "MÉXICO", "NICARAGUA", "NORUEGA", "NUEVA ZELANDA",
  "PAÍSES BAJOS", "PANAMÁ", "PARAGUAY", "PERÚ", "POLONIA", "PORTUGAL", "PUERTO RICO", "REINO UNIDO",
  "REPÚBLICA CHECA", "REPÚBLICA DOMINICANA", "RUSIA", "SINGAPUR", "SUDÁFRICA", "SUECIA", "SUIZA",
  "TAILANDIA", "TAIWÁN", "TURQUÍA", "UCRANIA", "URUGUAY", "VENEZUELA", "VIETNAM",
];
